#pragma once

#define BUZZER_PIN (GPIO_PIN_0)
#define BUZZER_PIN_PORT (GPIOB)

#define TIP_PIN (GPIO_PIN_3)
#define TIP_PIN_PORT (GPIOB)

#define RING1_PIN (GPIO_PIN_4)
#define RING1_PIN_PORT (GPIOB)

#define LDC_SCL_PIN (GPIO_PIN_9)
#define LCD_SCL_PIN_PORT (GPIOA)

#define LDC_SDA_PIN (GPIO_PIN_10)
#define LDC_SDA_PIN_PORT (GPIOA)